<?php
/**
 * Product view template
 *
 * @var $block \Azra\PriceRequest\Block\Price\Request
 */

 ?>
<?php
    $_product = $block->getProduct();
    if (!$_product instanceof \Magento\Catalog\Model\Product) {
        return;
    }
 ?>
<?php if ($block->isEnabled()): ?>
    <div class="price-request">
        <div class="action">
            <a href="" id="price-request-btn" class="action submit primary"><?php echo $block->escapeHtml(__("Price quote form"))?></a>
        </div>
        <div id="price-request-modal" style="display: none">
            <div class="modal-content-wrapper">
                <div class="request-messages-wrapper"></div>
                <form class="form form-price-request"
                    action="<?= $block->escapeUrl($block->getFormAction()) ?>"
                    method="post"
                    id="price-request-form"
                    autocomplete="off">
                    <fieldset class="fieldset create info">
                        <input type="hidden" name="product_sku" value="<?php echo $_product->getSku() ?>">
                        <input type="hidden" name="hideit" value="">
                        <div class="field required">
                            <label for="user_full_name" class="label"><span><?= $block->escapeHtml(__('Full Name')) ?></span></label>
                            <div class="control">
                                <input type="text" name="user_full_name" autocomplete="user_full_name" id="user_full_name" value="<?php echo $block->escapeHtmlAttr($block->getCustomerName()) ?>" title="<?= $block->escapeHtmlAttr(__('Full Name')) ?>" class="input-text" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field required">
                            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                            <div class="control">
                                <input type="email" name="email" autocomplete="email" id="email_address" value="<?php echo $block->escapeHtmlAttr($block->getCustomerEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field">
                            <label for="comment" class="label"><span><?= $block->escapeHtml(__('Message')) ?></span></label>
                            <div class="control">
                                <textarea name="comment" id="comment" cols="30" rows="10" title="<?= $block->escapeHtmlAttr(__('Message')) ?>" class="input-text"></textarea>
                            </div>
                        </div>
                    </fieldset>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit" class="action submit primary" title="<?= $block->escapeHtmlAttr(__('Submit Request')) ?>"><span><?= $block->escapeHtml(__('Submit Request')) ?></span></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#price-request-form": {
                "priceRequest": {
                    "modalButtonId": "#price-request-btn",
                    "priceRequestModalId": "#price-request-modal",
                    "messageContainer": ".request-messages-wrapper"
                }
            }
        }
    </script>
<?php endif ?>
